"""
Quản lý macro: lưu, đọc, xóa macro dạng JSON
"""

import json
import os
from pathlib import Path
from datetime import datetime

PROJECT_DIR = Path(__file__).parent
MACROS_DIR = PROJECT_DIR / "macros"
DATASET_DIR = PROJECT_DIR / "dataset"


def _ensure_dirs():
    os.makedirs(MACROS_DIR, exist_ok=True)
    os.makedirs(DATASET_DIR, exist_ok=True)


def save_macro(name: str, steps: list[dict]) -> str:
    """
    Lưu macro ra file JSON.
    steps: list các dict {timestamp, type, label, x, y, image_crop, text_content}
    Trả về đường dẫn file.
    """
    _ensure_dirs()

    macro = {
        "name": name,
        "created_at": datetime.now().isoformat(),
        "steps": steps,
    }

    filepath = MACROS_DIR / f"{name}.json"
    with open(filepath, "w", encoding="utf-8") as f:
        json.dump(macro, f, ensure_ascii=False, indent=2)

    return str(filepath)


def load_macro(name: str) -> dict | None:
    """Đọc macro từ file JSON"""
    filepath = MACROS_DIR / f"{name}.json"
    if not filepath.exists():
        # Thử tìm với tên khác (có thể không có .json)
        for f in MACROS_DIR.glob(f"{name}*"):
            filepath = f
            break
        else:
            return None

    with open(filepath, "r", encoding="utf-8") as f:
        return json.load(f)


def list_macros() -> list[str]:
    """Liệt kê tất cả macro đã lưu"""
    _ensure_dirs()
    macros = []
    for f in MACROS_DIR.glob("*.json"):
        macros.append(f.stem)
    return sorted(macros)


def delete_macro(name: str) -> bool:
    """Xóa macro"""
    filepath = MACROS_DIR / f"{name}.json"
    if filepath.exists():
        os.remove(filepath)
        return True
    return False


def save_to_dataset(label: str, image_path: str, x_center: float, y_center: float,
                    img_width: int, img_height: int) -> tuple[str, str]:
    """
    Lưu ảnh crop + label YOLO format vào dataset.
    Trả về (path ảnh, path label).
    """
    _ensure_dirs()

    class_dir = DATASET_DIR / label
    os.makedirs(class_dir, exist_ok=True)

    # Đếm số ảnh hiện có
    existing = list(class_dir.glob(f"{label}_*.png"))
    idx = len(existing) + 1

    # Copy ảnh vào dataset
    import shutil
    dst_img = class_dir / f"{label}_{idx:03d}.png"
    shutil.copy(image_path, dst_img)

    # Tạo label YOLO format (normalized)
    # Format: class_id x_center y_center width height
    # Lưu ý: đây là crop, nên bounding box là toàn bộ ảnh
    dst_label = class_dir / f"{label}_{idx:03d}.txt"
    with open(dst_label, "w") as f:
        # class_id = 0 (sẽ cập nhật khi tạo data.yaml)
        f.write(f"0 0.5 0.5 1.0 1.0\n")

    return str(dst_img), str(dst_label)


def generate_yaml() -> str:
    """Tạo file data.yaml cho YOLO training"""
    _ensure_dirs()

    # Tìm tất cả class
    classes = []
    for d in DATASET_DIR.iterdir():
        if d.is_dir():
            classes.append(d.name)

    if not classes:
        return ""

    classes.sort()
    yaml_path = DATASET_DIR / "data.yaml"
    yaml_content = f"""# Auto-generated by TikTok Auto Bot
path: {DATASET_DIR}
train: {DATASET_DIR}
val: {DATASET_DIR}

nc: {len(classes)}
names: {json.dumps(classes)}
"""
    with open(yaml_path, "w", encoding="utf-8") as f:
        f.write(yaml_content)

    return str(yaml_path)


def get_dataset_stats() -> dict:
    """Thống kê dataset"""
    _ensure_dirs()
    stats = {}
    for d in DATASET_DIR.iterdir():
        if d.is_dir():
            png_count = len(list(d.glob("*.png")))
            stats[d.name] = png_count
    return stats
